/* The Matrix trilogy journey: finale endings. Content only (Opus pass).
   Evaluated in order after the aftertaste (ch09); the first `when` that holds wins. Every finale path has exactly one of
   peaceHold / sequel / wakeAll from ch09, so rules are grouped by those flags; the last three are safety fallbacks and do
   not count in the gallery. Neo dies only with "sacrifice" (ch08 a); "brawl" and "smithTalked" leave him alive and blind.
   Trinity is dead with "trinityLost" (ch06 b) or "crash" (ch07 a); she survives with "trinitySafe" (ch07 c) or
   "defendZion" (ch07 b). {meter} in share lines = final belief score. */
(window.JOURNEYS = window.JOURNEYS || {});
(window.JOURNEYS["matrix"] = window.JOURNEYS["matrix"] || {}).endings = [
  /* "Until the sequel" */
  {id: "sheComesBack", when: "askedTrinity && sequel", name: "She Comes Back",
   summary: "Neo asked a face made of insects for one person back, and sixty years later a studio asks for a sequel about exactly that. The Analyst builds a coffee shop, two people who do not remember each other order the same drink, and somebody makes a great deal of money.",
   share: "My timeline: She Comes Back. Neo asked the machines for Trinity, and got a sequel. Belief {meter}/100."},
  {id: "nightclubRematch", when: "sequel && merovFight", name: "Nightclub Rematch",
   summary: "A very old program with a grudge, an unpaid restaurant bill and six hundred years of free time gets a whole subplot to himself. He spends it in a nightclub, shouting, and he is the best thing in the film.",
   share: "My timeline: Nightclub Rematch. Neo wrecked the Frenchman's restaurant and paid for it in the sequel. Belief {meter}/100."},
  {id: "smithOwesHim", when: "sequel && smithTalked", name: "Smith Owes Him One",
   summary: "Smith comes back in the sequel with a new face and an old grudge, and then, to everyone's surprise, helps. It turns out being asked how you feel, once, in the rain, goes a long way.",
   share: "My timeline: Smith Owes Him One. Neo talked Smith down, and Smith paid it back. Belief {meter}/100."},
  {id: "thomasTiffany", when: "sequel && trinity>=60 && !trinityLost", name: "Thomas and Tiffany",
   summary: "Neo and Trinity wake up in a new Matrix with new names, at neighboring tables in a coffee shop. It takes them a whole film to remember each other, and she is the one who flies this time.",
   share: "My timeline: Thomas and Tiffany. Neo and Trinity found each other again, sixty years later. Belief {meter}/100."},
  {id: "mandatorySequel", when: "sequel && belief>=85", name: "Mandatory Sequel",
   summary: "The machines rebuild the One because a legend that big is good for business. Thomas Anderson spends the sequel making a game about his own life, under protest, and it sells very well.",
   share: "My timeline: Mandatory Sequel. Neo believed so hard they had to bring him back. Belief {meter}/100."},
  {id: "heNeverLanded", when: "sequel && flewAway", name: "He Never Landed",
   summary: "Neo goes up through a courtyard roof and more or less keeps going, and the sequel is about a man who has learned that the fastest way out of any room is straight up. The Smiths are still down there, still multiplying, still counting.",
   share: "My timeline: He Never Landed. Straight up, out of every room. Belief {meter}/100."},
  {id: "sheDroveItHerself", when: "sequel && trustedThem", name: "She Drove It Herself",
   summary: "Neo stayed off the freeway and two people who were doing this before he arrived did it themselves, badly, brilliantly and at enormous cost. The sequel belongs to them. He is in it, and he is not the reason any of it works.",
   share: "My timeline: She Drove It Herself. He stayed away and they did it anyway. Belief {meter}/100."},
  {id: "versionSeven", when: "sequel", name: "Version Seven",
   summary: "The Architect is retired and a friendlier program runs a friendlier Matrix, with more cats. Neo lives in it without knowing, and so, for a while, does everyone else.",
   share: "My timeline: Version Seven. The peace held until somebody rebuilt the Matrix. Belief {meter}/100."},

  /* "Wake everyone up" */
  {id: "emptyBlock", when: "wakeAll && stoodAndFought", name: "The Block That Was Empty",
   summary: "Neo stayed in that courtyard for forty minutes and won every single exchange, and by the end there was nobody left on the street who was not Smith. When everybody is unplugged at once the first thing anyone does is a headcount, and that block comes back short.",
   share: "My timeline: The Block That Was Empty. He won the fight and the street paid for it. Belief {meter}/100."},
  {id: "theOnRamp", when: "wakeAll && earlyOnTheFreeway", name: "The On-Ramp",
   summary: "He was standing on the on-ramp before the chase could start, and nobody on that road was hurt at all, which had never happened before and was filmed by several hundred people. After that the system stopped treating him as an anomaly to contain and started planning around him, and everything that came afterwards came in larger numbers.",
   share: "My timeline: The On-Ramp. Nobody died on that freeway, and the system noticed. Belief {meter}/100."},
  {id: "breakfast", when: "wakeAll && zion>=80", name: "Breakfast for Billions",
   summary: "Zion survives the siege and then the refugees: a few billion hungry people and one kitchen. The porridge runs out on day three. The machines, to their own surprise, start farming.",
   share: "My timeline: Breakfast for Billions. Neo saved Zion and then everyone moved in. Belief {meter}/100."},
  {id: "nobodyToChase", when: "wakeAll && agents>=60", name: "Nobody Left to Chase",
   summary: "With every human unplugged, the Agents have nobody to chase. They keep patrolling the empty city anyway, in pairs, sunglasses on, and one of them eventually takes up jogging.",
   share: "My timeline: Nobody Left to Chase. Everybody woke up and the Agents were out of a job. Belief {meter}/100."},
  {id: "everybodyOut", when: "wakeAll", name: "Everybody Out",
   summary: "The whole human race wakes up at once, in the dark, hungry and furious about the cables. It is a very hard year. It is also the first one in centuries that is actually theirs.",
   share: "My timeline: Everybody Out. Neo's peace woke up the whole world. Belief {meter}/100."},

  /* "As long as it can" */
  {id: "manager", when: "peaceHold && manager", name: "Speak to the Manager",
   summary: "The peace holds, and the Architect is formally reprimanded by the machines for customer service failures. Neo's complaint is framed and hung in the Source, next to the org chart.",
   share: "My timeline: Speak to the Manager. Neo asked the Architect for a supervisor and got one. Belief {meter}/100."},
  {id: "openDoor", when: "peaceHold && freeAll", name: "The Open Door",
   summary: "The war ends with a clause instead of a ceasefire: anybody who works out that something is wrong may leave, once a year, and nobody follows them. Zion doubles in eleven years, then stops being called Zion, because it needs a bigger word.",
   share: "My timeline: The Open Door. Neo negotiated a way out for anyone who asks. Belief {meter}/100."},
  {id: "weWillSee", when: "peaceHold && askedTrinity", name: "We Will See",
   summary: "The machines never say no. They say we will see, and then the peace holds for sixty years while somewhere in a building nobody has drawn yet a project file sits open with one name in it.",
   share: "My timeline: We Will See. Neo asked for Trinity and the machines did not say no. Belief {meter}/100."},
  {id: "theConnection", when: "peaceHold && karma", name: "The Connection",
   summary: "A program in a train station told Neo that love is only a word for a connection, and Neo spent the last forty minutes of the war behaving like a man who had been told something true. Sati paints the sunrise. He asked her to.",
   share: "My timeline: The Connection. A program in a station explained love to the One. Belief {meter}/100."},
  {id: "vase", when: "peaceHold && vase && sacrifice", name: "The Vase",
   summary: "The Oracle bakes cookies for anyone who comes to the door and keeps a new vase in the hall. Children who visit are told not to worry about it. None of them ever breaks it.",
   share: "My timeline: The Vase. Neo cared more about the pottery than the prophecy. Belief {meter}/100."},
  {id: "notTheOne", when: "peaceHold && sacrifice && belief<60", name: "Not the One",
   summary: "Neo never quite believed he was the One, and he saved everybody anyway. The Oracle, asked about it later, says that was always the point, and has another cookie.",
   share: "My timeline: Not the One. Neo never believed it and did it anyway. Belief {meter}/100."},
  {id: "sunrise", when: "peaceHold && sacrifice && crash && belief>=80", name: "The Sunrise",
   summary: "The timeline closest to the films. Neo and Trinity are gone, Zion is saved, and a little girl paints a sunrise for them. Whether we see Neo again is left, pointedly, open.",
   share: "My timeline: The Sunrise. Almost exactly what happened on screen. Belief {meter}/100."},
  {id: "stayed", when: "peaceHold && sacrifice && trinitySafe && !trinityLost", name: "The One Who Stayed",
   summary: "Trinity lives because Neo left her behind, and she never entirely forgives him for it. She flies the first ship out of Zion into open sky, and takes his old coat.",
   share: "My timeline: The One Who Stayed. Neo went alone, and Trinity lived. Belief {meter}/100."},
  {id: "theInvitation", when: "peaceHold && letHimCopy && belief>=70", name: "The Invitation",
   summary: "Neo put his hands down in a courtyard years earlier and learned that the copying was never a weapon, it was an offer. He spends the rest of it knowing exactly how this ends and telling nobody, which is either the loneliest thing in the trilogy or the kindest.",
   share: "My timeline: The Invitation. He knew the ending from the courtyard. Belief {meter}/100."},
  /* Moved above the single-flag rules below: merovDeal and cheatJump are each one choice in one early
     chapter, and rules that broad were swallowing every run that had them. */
  {id: "theNapkin", when: "peaceHold && merovDeal", name: "The Napkin",
   summary: "Peace holds, and a woman in a white dress produces a napkin with terms written on it in a language nobody at the table read. The exiles get their place in the new world, and the Frenchman pretends he is not delighted.",
   share: "My timeline: The Napkin. Neo paid the Frenchman in something that was not money. Belief {meter}/100."},
  {id: "lowerGravity", when: "peaceHold && cheatJump", name: "Lower the Gravity",
   summary: "The war is won by a man who never once freed his mind and instead kept asking who was running the program and where the settings were. Morpheus is still annoyed about it. Tank has written a book.",
   share: "My timeline: Lower the Gravity. Neo edited the program instead of believing in it. Belief {meter}/100."},
  {id: "blindChampion", when: "peaceHold && brawl", name: "Blind Champion",
   summary: "Neo beats Smith the hard way and lives, blind in the real world and flawless in the Matrix. He teaches kung fu to the newly freed, and nobody lands a punch on him, ever.",
   share: "My timeline: Blind Champion. Neo refused the ending and won the fight. Belief {meter}/100."},
  {id: "smithRetired", when: "peaceHold && smithTalked", name: "Smith, Retired",
   summary: "The Smith virus is gone, but somewhere in the Matrix a quiet man in a dark suit feeds the pigeons every morning. He has never been happier. Neo visits him on Sundays.",
   share: "My timeline: Smith, Retired. Neo asked Smith what he wanted, and gave it to him. Belief {meter}/100."},
  {id: "rightDoor", when: "peaceHold && trinityLost", name: "The Right Door",
   summary: "Neo chose Zion over Trinity, and Zion lives. They build a statue of him at the dock. He would have hated it, and she would have told him so.",
   share: "My timeline: The Right Door. Neo picked Zion over Trinity. Belief {meter}/100."},
  {id: "forMorpheus", when: "peaceHold && morpheusDead", name: "For Morpheus",
   summary: "The war ends the way Morpheus always said it would, without Morpheus. Zion names its first ship built in peacetime after him, and the crew insist on wearing sunglasses indoors.",
   share: "My timeline: For Morpheus. The prophecy came true without the man who believed it. Belief {meter}/100."},
  {id: "holdTheDock", when: "peaceHold && defendZion", name: "Hold the Dock",
   summary: "Neo fought Smith from a chair on Zion's own dock and died there, with Trinity holding his hand. When the Sentinels turn back, Zion throws its victory party in his name, which, as tradition demands, is mostly drums and dancing in a cave.",
   share: "My timeline: Hold the Dock. Neo stayed to defend Zion. Belief {meter}/100."},
  {id: "otherFile", when: "peaceHold && informant", name: "The Other File",
   summary: "Peace holds, and one document survives the war in a system nobody switched off: a signed agreement in which Thomas Anderson promised to help catch Morpheus. It is read out at every anniversary by people who think it is a joke.",
   share: "My timeline: The Other File. Neo took Smith's deal in the first hour and lived with it. Belief {meter}/100."},
  {id: "manWhoChecked", when: "peaceHold && noJump", name: "The Man Who Checked",
   summary: "He refused the jump on the first day and said so out loud, and then believed nothing he had not verified himself, all the way to the Machine City. It takes longer. It works.",
   share: "My timeline: The Man Who Checked. Neo never believed anything he had not checked. Belief {meter}/100."},
  /* Every peaceHold run now matches one of the rules above, so this no longer catches anything and is kept
     only as the safety net for that group. Marked fallback, which takes it out of the gallery count:
     an ending nobody can reach should not be advertised as findable. */
  {id: "truce", when: "peaceHold", fallback: true, name: "The Truce",
   summary: "The machines keep their word, and so do the humans, mostly. Nobody quite trusts the peace, which is probably why it lasts.",
   share: "My timeline: The Truce. Neo won the peace. Belief {meter}/100."},
  {id: "theOne", fallback: true, when: "belief>=80", name: "The One",
   summary: "Whatever else happened, he believed it, and it was true.",
   share: "My timeline: The One. Belief {meter}/100."},
  {id: "neo", fallback: true, when: "belief>=40", name: "Neo",
   summary: "Half hacker, half messiah, and never fully sure which.",
   share: "My timeline: Neo. Belief {meter}/100."},
  {id: "mrAnderson", fallback: true, when: "", name: "Mr. Anderson",
   summary: "In the end he was mostly what Smith always called him: Mr. Anderson.",
   share: "My timeline: Mr. Anderson. Belief {meter}/100."}
];
