/* Breaking Bad journey: finale endings. Content only (Opus pass).
   Evaluated in order after the last chapter played (ch11a or ch11b at n:23, the aftertaste); the first `when` that holds wins.
   Every finale path has exactly one of surrendered / shootout / deal from ch10.js (n:19), plus one n:23 flag:
   shootout runs play ch11a (gunTrunk / jackDeal / jesseKeys), the others play ch11b (confessed / lectured / silent).
   Rules are grouped by those flags; the last three are safety fallbacks and do not count in the gallery.
   {meter} in share lines = final darkness score. */
(window.JOURNEYS = window.JOURNEYS || {});
(window.JOURNEYS["breaking-bad"] = window.JOURNEYS["breaking-bad"] || {}).endings = [
  /* Nobody fired: ch17-standoff.js (n:20) choice a or c. Checked before everything else, because a desert
     where no shot was fired changes more than any decision taken afterwards. */
  {id: "quietDesert", when: "noShots && confessed", name: "The Quiet Desert",
   summary: "Not one round was fired at To'hajiilee, so there is nothing to bury and nobody to mourn, and the trial is about chemistry and tax law. Hank testifies for two days and then goes back to work, which is all he ever wanted.",
   share: "My timeline: The Quiet Desert. Nobody fired a shot in the desert. Heisenberg meter {meter}/100."},
  {id: "nobodyFired", when: "noShots && hostages", name: "Nobody Fired",
   summary: "Two federal agents spend six weeks in a shed and come out alive, which is six weeks longer than the show gave them. Walt is a free man with the best-informed witnesses in the country and a compound full of people who now call him a partner.",
   share: "My timeline: Nobody Fired. Walt talked Jack out of a gunfight and took hostages instead. Heisenberg meter {meter}/100."},
  /* Above The Standoff so that a run which crossed neither line gets its own name for it. boySafe comes from
     ch11-deadfreight.js (n:11), the two lines being the boy on the ridge and the first shot in the desert. */
  {id: "notTheKid", when: "noShots && boySafe", name: "The Two He Did Not Cross",
   summary: "No shot was fired in that desert, and years earlier a boy on a dirt bike rode home from a train robbery with a story nobody believed. Every other line Walt crossed is on the indictment. These are the two he did not, and they are the only two his son ever asks him about.",
   share: "My timeline: The Two He Did Not Cross. No shot in the desert, and the kid rode home. Heisenberg meter {meter}/100."},
  {id: "theOldManSaidYes", when: "noShots && hectorHelped", name: "The Old Man Said Yes",
   summary: "Not one round was fired in that desert, and years before it a man in a wheelchair who could only say yes or no chose the right moment to say yes. Walt spent the rest of his life arranging other people, and the two times it went well were the two times he asked first.",
   share: "My timeline: The Old Man Said Yes. He asked the old man instead of using him. Heisenberg meter {meter}/100."},
  {id: "theStandoff", when: "noShots", name: "The Standoff",
   summary: "Ninety seconds of shouting in the dirt, and then everybody drove away. Walt lost the money, the partner and the case, and kept the one thing he never asks for: a family that is all still alive.",
   share: "My timeline: The Standoff. Ninety seconds of shouting, and not one shot. Heisenberg meter {meter}/100."},

  /* Gave up in New Hampshire (ch25-granite.js choice c): the run never plays Felina, so without these two it would
     fall through every group below and land on a safety fallback. Checked right after the no-shots group. */
  {id: "theBarStool", when: "gaveUp && confessed", name: "The Bar Stool",
   summary: "He gave his own name to a field office from a payphone in New Hampshire and then did the hard part, which was staying on the stool while the television explained that he had never contributed anything to anything. He told them where the barrel was on the first morning, and nobody has ever been able to account for that.",
   share: "My timeline: The Bar Stool. He called it in and then waited. Heisenberg meter {meter}/100."},
  {id: "pageEleven", when: "gaveUp", name: "Page Eleven",
   summary: "There is no compound, no last drive and no final list. There is a hearing schedule, an enormous amount of cooperation, and a man who gets steadily smaller in the newspapers until he is a paragraph on page eleven, which is the one punishment he never planned for.",
   share: "My timeline: Page Eleven. He turned himself in from a bar in New Hampshire. Heisenberg meter {meter}/100."},

  /* Hank lived: only reachable on shootout runs, through ch17-jack.js (n:21). Checked first, because a living
     federal agent changes every finale more than anything Walt does at the compound afterwards. */
  /* Top of the hankLives group: every atLarge run ends on gunTrunk, jackDeal or jesseKeys, so a rule placed
     below those three could never fire. A confession given months earlier outranks all of them anyway. */
  {id: "theGarageConfession", when: "hankLives && cameClean", name: "The Garage Confession",
   summary: "Walt told Hank all of it on a garage floor months before the desert, sitting on the concrete with his back against a shelf, and Hank walked out of To'hajiilee alive to write it down. It is the most complete case the district has ever filed and it is built almost entirely out of the defendant's own patience.",
   share: "My timeline: The Garage Confession. Walt told Hank everything, and Hank lived to write it down. Heisenberg meter {meter}/100."},
  {id: "oneMinute", when: "hankLives && warnedHank", name: "One Minute",
   summary: "Years before the desert, Walt spent nine words and about four seconds on a payphone and gave a federal agent one minute of warning, and one minute turned out to be enough. Hank never learns who called. He plays the recording to himself about once a month for the rest of his life.",
   share: "My timeline: One Minute. Nine words from a payphone, and Hank walked away twice. Heisenberg meter {meter}/100."},
  {id: "soldNotSaved", when: "hankLives && soldJesse", name: "Sold, Not Saved",
   summary: "Hank lives, testifies, and spends the rest of his career quoting one sentence from the desert to juries. Walt bought a brother-in-law and paid for him with a partner, and both of them know the exchange rate.",
   share: "My timeline: Sold, Not Saved. Hank lived, because Walt handed Jack the cook. Heisenberg meter {meter}/100."},
  {id: "hostagePrice", when: "hankLives && !soldJesse && family>=80", name: "The Hostage Price",
   summary: "Eighty million dollars bought one life in a desert, which is the only trade in this entire story that Walt never tries to explain or justify. He simply pays it and never mentions it again.",
   share: "My timeline: The Hostage Price. Walt paid everything, once, for somebody else. Heisenberg meter {meter}/100."},
  {id: "hankGetsHim", when: "hankLives && gunTrunk", name: "Hank Gets Him",
   summary: "Walt settles every account at the compound and gets exactly as far as the county line. Hank is waiting at the roadblock he built himself, off duty, unarmed and extremely patient.",
   share: "My timeline: Hank Gets Him. Walt bought Hank's life, and Hank spent it arresting him. Heisenberg meter {meter}/100."},
  {id: "twoSurvivors", when: "hankLives && jesseKeys", name: "Two Survivors",
   summary: "Jesse decides how the compound ends, and Hank decides how Walt does. The two men who spent five seasons being ruined by Walter White are the only two still standing at the end of this one.",
   share: "My timeline: Two Survivors. Hank lived, Jesse chose, and Walt did neither. Heisenberg meter {meter}/100."},
  {id: "federalWitness", when: "hankLives && jackDeal", name: "Federal Witness",
   summary: "Walt takes Jack's deal and drives away with his barrels, into a country where his brother-in-law is on television twice a week describing him. He is recognized in a diner in Nebraska within a month.",
   share: "My timeline: Federal Witness. Walt kept the money and Hank kept the microphone. Heisenberg meter {meter}/100."},


  /* Shootout, then "Felina" (ch11a) */
  {id: "theFoundation", when: "moneyOnly", name: "A Charitable Foundation with a Dull Name",
   summary: "He drove eighteen hundred miles for one conversation in a living room, said almost nothing, and went back north. On his son's eighteenth birthday a great deal of money arrives from strangers, and the family spends a long evening deciding whether to keep it. They keep it.",
   share: "My timeline: A Charitable Foundation with a Dull Name. He went back for the money and nothing else. Heisenberg meter {meter}/100."},
  {id: "theBenchInThePlaza", when: "gunTrunk && plazaTruth", name: "The Bench in the Plaza",
   summary: "He settles every account at the compound, and the only conversation he replays on the drive is a bench in a public square where he said all of it out loud and was not forgiven. Jesse walked off across that square without looking round, and lived, which is more than the other version manages.",
   share: "My timeline: The Bench in the Plaza. He told Jesse the truth in a public square. Heisenberg meter {meter}/100."},
  {id: "sideBySide", when: "gunTrunk && jesse>=80", name: "Side by Side",
   summary: "Jesse drives, and Walt rides in the passenger seat for the first time since the RV. They make it as far as a hospital in Farmington. Walt insists on correcting the doctor's chemistry.",
   share: "My timeline: Side by Side. Jesse drove Walt away from Jack's compound. Heisenberg meter {meter}/100."},
  {id: "janeDrives", when: "gunTrunk && janeAlive", name: "Jane Drives the Getaway Car",
   summary: "Jane was waiting down the road with the engine running, and nobody asks how she knew where to come. She and Jesse leave New Mexico for good. Walt stays behind with the equipment.",
   share: "My timeline: Jane Drives the Getaway Car. Jane lived, and it mattered in the end. Heisenberg meter {meter}/100."},
  {id: "mikeWaiting", when: "mikeLives && gunTrunk", name: "Mike Was Waiting",
   summary: "A man who retired properly reads about the compound in a newspaper two time zones away, folds it, and finishes his coffee. He sends Jesse a bus ticket and no note, because notes are evidence.",
   share: "My timeline: Mike Was Waiting. Walt let Mike retire, and Mike quietly returned the favor. Heisenberg meter {meter}/100."},
  /* Keyed on boySafe, not on drewDead, so that the all-canon walk still lands on Felina itself. */
  {id: "theBoyLived", when: "gunTrunk && boySafe", name: "The Boy on the Ridge Lived",
   summary: "Walt settles every account at the compound and goes down on a laboratory floor with the same list of names as always, minus one. Somewhere south of Alamogordo a man in his twenties rides a dirt bike badly at weekends and has no idea he was ever on anybody's list.",
   share: "My timeline: The Boy on the Ridge Lived. One name that never made it onto the list. Heisenberg meter {meter}/100."},
  {id: "felina", when: "gunTrunk", name: "Felina",
   summary: "The timeline closest to the show. Walt settles every account, frees Jesse, and dies on the floor of a meth lab, among the only things he ever fully trusted.",
   share: "My timeline: Felina. Almost exactly what happened on TV. Heisenberg meter {meter}/100."},
  {id: "packageDeal", when: "jackDeal && jesse>=40", name: "Package Deal",
   summary: "Walt and Jesse drive out of the compound in separate cars and never speak again. Jack's crew sells Todd's cloudy imitation as the real thing, and within a year the name Heisenberg is a joke in three states.",
   share: "My timeline: Package Deal. Walt took Jack's deal and got Jesse out in it. Heisenberg meter {meter}/100."},
  {id: "victorsBlue", when: "victorLives && jackDeal", name: "Victor's Blue",
   summary: "Walt spared a man in a laundry years ago, and that man has been cooking ever since. Within a year the blue on the street is Victor's, it is better than Todd's, and nobody in three states has any idea who Heisenberg was.",
   share: "My timeline: Victor's Blue. Walt saved Victor, and Victor took the business. Heisenberg meter {meter}/100."},
  {id: "cleanGetaway", when: "jackDeal && carwash", name: "Clean Getaway",
   summary: "Walt drives his barrels from one car wash to the next, laundering as he goes, like a man in a very clean witness protection program. The trunk stays shut for good.",
   share: "My timeline: Clean Getaway. Walt took Jack's deal and vanished into his own car washes. Heisenberg meter {meter}/100."},
  {id: "signedAndGone", when: "jackDeal && signedConfession", name: "Nine Pages, Posted",
   summary: "Walt shakes hands with Jack and keeps the empire, and the nine signed pages that clear his wife are already sitting in three separate post boxes. He is a free man, his family is legally innocent, and there is nobody left alive who would sit at his table.",
   share: "My timeline: Nine Pages, Posted. Walt kept the empire and cleared her name by post. Heisenberg meter {meter}/100."},
  {id: "kingOfNothing", when: "jackDeal", name: "King of Nothing",
   summary: "Walt gets some of his money back and none of anything else. The cancer returns in the spring. He spends it alone in a rented house, next to barrels he no longer has any use for.",
   share: "My timeline: King of Nothing. Walt took Jack's deal and kept almost nothing. Heisenberg meter {meter}/100."},
  {id: "ambulance", when: "jesseKeys && jesse>=70", name: "The Ambulance",
   summary: "Walt survives the night because Jesse decided he should. He is tried from a hospital bed and serves what is left of his life in a prison ward. Jesse visits once, to say he is never visiting again.",
   share: "My timeline: The Ambulance. Walt gave Jesse the keys and Jesse saved his life. Heisenberg meter {meter}/100."},
  {id: "jessesCall", when: "jesseKeys", name: "Jesse's Call",
   summary: "Jesse drives north and does not look back. Walt answers one last call on Todd's phone, from Lydia, and makes one more, to 911. The police find him sitting up, waiting for them.",
   share: "My timeline: Jesse's Call. Walt gave Jesse the keys and let him decide. Heisenberg meter {meter}/100."},

  /* Surrender, then sentencing (ch11b) */
  /* Moved above the other two confessed rules: darkness at or under 30 after twenty-five chapters is the
     rarest thing a run can do, and it was being swallowed by the jesse and family variants below. */
  {id: "almostGood", when: "surrendered && confessed && darkness<=30", name: "Almost a Good Man",
   summary: "Walt surrenders with his conscience mostly intact and admits the rest in open court. He did terrible things, but fewer than he could have, and in this timeline that turns out to matter.",
   share: "My timeline: Almost a Good Man. Walt surrendered before he became Heisenberg. Heisenberg meter {meter}/100."},
  /* Below almostGood on purpose: that one is already the rarest rule in the journey and must keep its runs. */
  {id: "characterWitness", when: "surrendered && confessed && jesse>=70", name: "Character Witness",
   summary: "Jesse testifies at sentencing, for Walt, and calls him the best teacher he ever had. The judge takes five years off, and the family is in the front row.",
   share: "My timeline: Character Witness. Walt surrendered and Jesse spoke for him. Heisenberg meter {meter}/100."},
  {id: "visitingHours", when: "surrendered && confessed && family>=60", name: "Visiting Hours",
   summary: "Walt goes to prison, and his family visits every Sunday. Holly learns to read from his letters, which are grammatically perfect.",
   share: "My timeline: Visiting Hours. Walt surrendered, told the truth, and his family kept visiting. Heisenberg meter {meter}/100."},
  {id: "threePrisons", when: "surrendered && tenInTwo", name: "Three Prisons, Two Minutes",
   summary: "He walks out from behind the rock with his hands up, and the file that follows him has ten counts of murder in it that no plea in the state will touch. The chemistry gets four pages at sentencing. The two minutes get four hundred.",
   share: "My timeline: Three Prisons, Two Minutes. The ten names were the only ones that mattered. Heisenberg meter {meter}/100."},
  {id: "herNameCleared", when: "surrendered && clearedSkyler", name: "Her Name, Cleared",
   summary: "Walt surrenders in the desert and then spends his one recorded call being the worst man he can convincingly be, at volume, for an audience of four listening officers. Skyler keeps the house. He keeps the sentence and the transcript, and she never tells anybody that she understood what he was doing.",
   share: "My timeline: Her Name, Cleared. One phone call, performed perfectly, for somebody else. Heisenberg meter {meter}/100."},
  {id: "thePayrollTrust", when: "surrendered && silentNine", name: "The Payroll That Outlived Him",
   summary: "Nine men in three prisons never said a word, because the money never stopped arriving, and it does not stop when Walt is sentenced either. A trust with a very boring name pays nine families every quarter for another eleven years, and not one investigator ever works out what it is for.",
   share: "My timeline: The Payroll That Outlived Him. Nine men, paid, quiet, for eleven years. Heisenberg meter {meter}/100."},
  {id: "theSharedSentence", when: "surrendered && sharedBlame", name: "The Shared Sentence",
   summary: "He surrenders and says nothing at all about his wife, which the prosecution reads, correctly, as permission. They are sentenced eleven days apart in the same building, and Marie drives Holly to two different visiting rooms for four years.",
   share: "My timeline: The Shared Sentence. He said nothing about her, and it cost her four years. Heisenberg meter {meter}/100."},
  /* The three new chapters get a home in the two biggest groups, so a first-season and a fourth-season choice
     can still decide the last screen. Placed below the Skyler rules, which are later and more decisive. */
  {id: "counselOfRecord", when: "surrendered && saulLoyal", name: "Counsel of Record",
   summary: "The lawyer Walt once tested with a fake address defends him for four months, badly paid and entirely straight. He gets the sentence down by nine years and never once mentions the Thursday Walt spent watching an empty door.",
   share: "My timeline: Counsel of Record. Walt tested his lawyer, and his lawyer showed up anyway. Heisenberg meter {meter}/100."},
  {id: "compoundInterest", when: "surrendered && portfolio", name: "Compound Interest",
   summary: "The barrels were seized in an afternoon. The portfolio takes the government eleven years, four jurisdictions and a forensic accountant who develops a grudging professional respect for a chemistry teacher.",
   share: "My timeline: Compound Interest. Walt surrendered, and his portfolio kept working without him. Heisenberg meter {meter}/100."},
  {id: "cellBlock", when: "surrendered && lectured", name: "Cell Block Chemistry",
   summary: "Walt teaches chemistry to the other inmates, and every one of them passes. The warden is thrilled until he learns which chapter they found most interesting.",
   share: "My timeline: Cell Block Chemistry. Walt surrendered and started teaching again. Heisenberg meter {meter}/100."},
  {id: "copycat", when: "surrendered && silent", name: "The Copycat",
   summary: "Walt never says another word about it. A year later blue product appears in Phoenix, and every agent in the Southwest spends the next season trying to find out who learned from him.",
   share: "My timeline: The Copycat. Walt said nothing, and somebody kept cooking. Heisenberg meter {meter}/100."},
  {id: "postcardMike", when: "surrendered && mikeLives", name: "Postcard From Mike",
   summary: "Twice a year a postcard arrives at the prison with no message, no signature and a different postmark. The guards assume it is a code. It is a man with a granddaughter, saying nothing at all, on purpose.",
   share: "My timeline: Postcard From Mike. Walt let Mike go, and Mike remembered it. Heisenberg meter {meter}/100."},
  {id: "theManWhoStayedWalter", when: "surrendered && talkedToTuco", name: "The Man Who Stayed Walter",
   summary: "He went up that staircase over the junkyard as a chemistry teacher with a folder and came back down as one, and in five years he never once told anybody to say his name. At sentencing there is no Heisenberg to sentence, which the prosecutor finds inconvenient and the judge finds worse.",
   share: "My timeline: The Man Who Stayed Walter. He never invented the name. Heisenberg meter {meter}/100."},
  {id: "theFirstStaircase", when: "surrendered && sentJesse", name: "The First Staircase",
   summary: "Walt walks out of the desert with his hands up, and the one thing Jesse says about him in eleven hours of interviews is about a metal staircase over a junkyard: who went up it, and who waited three streets away with the engine running.",
   share: "My timeline: The First Staircase. He sent Jesse up, and Jesse never forgot which car he waited in. Heisenberg meter {meter}/100."},
  {id: "elevenPeopleEatingChicken", when: "surrendered && ownHands", name: "Eleven People Eating Chicken",
   summary: "That one he did himself, through the front door, at lunchtime, in a room with a camera in the corner. The footage is nine seconds long, has been enhanced four times, and is the first exhibit at every hearing he ever attends.",
   share: "My timeline: Eleven People Eating Chicken. He stopped arranging things and did one himself. Heisenberg meter {meter}/100."},
  {id: "theCardigan", when: "surrendered && theDVD", name: "Exhibit One Is a Cardigan",
   summary: "He walks out of the desert with his hands up, and the prosecution opens with fifty-one minutes of him at his own kitchen table in a cardigan, crying real tears while naming the wrong man. Every checkable fact in it is true, which is what makes the jury so quiet.",
   share: "My timeline: Exhibit One Is a Cardigan. His own tape, played back at his own trial. Heisenberg meter {meter}/100."},
  {id: "theRightName", when: "surrendered && soldHank", name: "The Right Name",
   summary: "He gave two men in grey suits a federal agent's name in a car park, and then surrendered to the same agent in a desert nine years later. Hank never finds out. Walt has to sit across a table from him in an interview room for four months knowing that he never will.",
   share: "My timeline: The Right Name. He pointed them at Hank himself, and Hank never knew. Heisenberg meter {meter}/100."},
  {id: "inmate", when: "surrendered", name: "Walter White, Inmate",
   summary: "Walt serves his sentence alone, writing long letters nobody answers. When the cancer comes back, he faces it the way he should have faced it the first time: honestly.",
   share: "My timeline: Walter White, Inmate. Walt surrendered, alone. Heisenberg meter {meter}/100."},

  /* Deal, then sentencing (ch11b) */
  {id: "bothOfThem", when: "deal && sharedBlame", name: "Both of Them",
   summary: "Walt trades everything he knows for protection for his family, and then leaves his wife's name sitting in the file untouched, which cancels most of what he just bought. The deal is honoured to the letter. The letter turns out to be a great deal shorter than he thought it was.",
   share: "My timeline: Both of Them. He bought protection and then forgot to name who for. Heisenberg meter {meter}/100."},
  {id: "coercedByADeadMan", when: "deal && blamedDead", name: "Coerced by a Dead Man",
   summary: "Walt hands over a version in which every fact is true and every arrangement of them is a lie, and Gus Fring, being dead, declines to correct it. Duress is extremely hard to disprove against a man who cannot take the stand. Walt is sentenced to nine years and is out in six.",
   share: "My timeline: Coerced by a Dead Man. Every fact true, and every fact in the wrong order. Heisenberg meter {meter}/100."},
  {id: "countFourteen", when: "deal && drewDead", name: "Count Fourteen",
   summary: "Forty pages, footnoted, and the prosecutor still opens with the same page every single time: a fourteen-year-old on a dirt bike who stopped to wave at a train. Walt is not charged with that one, because he did not do it, and no jury in the state hears the difference.",
   share: "My timeline: Count Fourteen. Everything he confessed, and the one thing he did not do. Heisenberg meter {meter}/100."},
  {id: "oneInsteadOfTen", when: "deal && lawyerOnly", name: "One Instead of Ten",
   summary: "He gives the DEA everything and explains, patiently, that he could have had ten men killed and chose one, as though arithmetic were a defence. The nine survivors testify one after another across five days, which is nine more witnesses than the state expected to have.",
   share: "My timeline: One Instead of Ten. He thought the number was the point. Heisenberg meter {meter}/100."},
  {id: "hankSaysNo", when: "deal && hank>=70", name: "Hank Says No",
   summary: "Hank has waited too long to settle for a deal. He takes the confession and the man, and gives Walt nothing but his own words read back to him in court.",
   share: "My timeline: Hank Says No. Walt offered everything and Hank took it all, without a deal. Heisenberg meter {meter}/100."},
  {id: "exhibitA", when: "deal && bookLab", name: "Exhibit A",
   summary: "The case was built by a task force, not by a brother-in-law, so nothing Walt offers is worth very much by the time he offers it. A paperback with a dedication in it is entered into evidence and read aloud in court, twice.",
   share: "My timeline: Exhibit A. Hank took the book to the office, and the book did the rest. Heisenberg meter {meter}/100."},
  {id: "pleaWax", when: "deal && carwash", name: "Plea Bargain With Wax",
   summary: "Walt trades the car wash books for immunity for Skyler. The chain is seized and sold at auction, and the new owners are delighted by how profitable it is.",
   share: "My timeline: Plea Bargain With Wax. Walt traded the car wash books for his family. Heisenberg meter {meter}/100."},
  {id: "lectureTour", when: "deal && lectured && galeAlive", name: "Lecture Tour",
   summary: "Part of the deal is a prison education program. Gale co-teaches it with him from the visitors' side of the glass, and brings the coffee machine.",
   share: "My timeline: Lecture Tour. Walt made a deal and ended up teaching chemistry with Gale. Heisenberg meter {meter}/100."},
  {id: "mrLambert", when: "deal && silent", name: "Mr. Lambert",
   summary: "Walt does his time under Skyler's maiden name in a unit for men who gave up too many names. Nobody there has heard of Heisenberg, and he finds that much harder than prison.",
   share: "My timeline: Mr. Lambert. Walt made a deal and disappeared under a borrowed name. Heisenberg meter {meter}/100."},
  {id: "offshoreTrust", when: "deal && portfolio", name: "The Offshore Trust",
   summary: "Walt hands over a network, a formula and a filing cabinet, and negotiates one thing for himself: the trust stays. Two children are put through college by a portfolio nobody in the family will discuss at dinner.",
   share: "My timeline: The Offshore Trust. Walt traded everything except the investments. Heisenberg meter {meter}/100."},
  {id: "noLawyer", when: "deal && noSaul", name: "No Lawyer Present",
   summary: "The man who never trusted a lawyer negotiates his own plea, alone, against three federal attorneys, and gets a deal that is eleven years worse than the one he was offered on day one. He is still proud of the footnotes.",
   share: "My timeline: No Lawyer Present. Walt cut out his lawyer and negotiated his own sentence. Heisenberg meter {meter}/100."},
  {id: "noNameOnTheFile", when: "deal && talkedToTuco", name: "No Name on the File",
   summary: "Forty pages of confession about a man who never had a street name, never wore the hat, and negotiated his first distribution deal with a folder and a margin calculation. Half the office thinks the file is about somebody else entirely. The other half is disappointed.",
   share: "My timeline: No Name on the File. A career built out of purity and margins. Heisenberg meter {meter}/100."},
  {id: "twoOldMen", when: "deal && hectorTalks", name: "Two Old Men and a Stenographer",
   summary: "Gus Fring went down because a man who could only ring a bell spent eleven hours spelling out names with one finger, and Walt hands over forty more pages years later. The two confessions end up filed in the same building, and the two men never meet again.",
   share: "My timeline: Two Old Men and a Stenographer. Hector talked, and eventually so did Walt. Heisenberg meter {meter}/100."},
  {id: "arrangedNotDone", when: "deal && theBell", name: "A Man Who Arranges Things",
   summary: "An old man in a wheelchair rang a bell and two people stopped existing three miles from where Walt was standing, which is exactly how he prefers it. He confesses to all of it in the flat voice of a project manager, and in forty pages he never once describes being in a room when anything happened.",
   share: "My timeline: A Man Who Arranges Things. He was never in the room, and that was the plan. Heisenberg meter {meter}/100."},
  /* Above hankSaysNo, which was catching one run in five on its own. */
  {id: "theSealedEnvelope", when: "deal && realDVD", name: "The Sealed Envelope",
   summary: "He confesses to a federal agent behind a rock in the desert, and a law firm in Santa Fe opens an envelope the same week containing fifty-one minutes of him saying the same things, unprompted, to a camera on his own kitchen table. The two versions match. Nobody can quite believe that.",
   share: "My timeline: The Sealed Envelope. He recorded the true one and posted it. Heisenberg meter {meter}/100."},
  {id: "theSouthernFile", when: "deal && tucoPartner", name: "The Southern File",
   summary: "Forty pages of confession, and the part the agents keep coming back to is eleven weeks in Mexico with a man who settled disagreements with his hands. There are photographs of it in a file that stayed open for years, with an older man in glasses standing at the edge of three of them.",
   share: "My timeline: The Southern File. He talked Tuco into a partnership and it went south, twice. Heisenberg meter {meter}/100."},
  {id: "nineHours", when: "deal && gaveJesse", name: "Nine Hours, Two Days",
   summary: "Walt stopped fighting it and let Jesse talk, and Jesse talked for nine hours across two days with a lawyer beside him. By the time Walt makes his own confession in the desert there is very little left in it that the DEA has not already heard, in somebody else's words, without the footnotes.",
   share: "My timeline: Nine Hours, Two Days. He let Jesse go and talk. Heisenberg meter {meter}/100."},
  {id: "theDeal", when: "deal", name: "The Deal",
   summary: "The family gets protection, the DEA gets the network, and Walt gets a small room and a long sentence. For once, he negotiated for someone else.",
   share: "My timeline: The Deal. Walt traded everything for his family's safety. Heisenberg meter {meter}/100."},

  {id: "heisenberg", fallback: true, when: "darkness>=85", name: "Heisenberg",
   summary: "Whatever else happened, the name outlived the man.",
   share: "My timeline: Heisenberg. Heisenberg meter {meter}/100."},
  {id: "walter", fallback: true, when: "darkness>=50", name: "Walter",
   summary: "Half teacher, half kingpin, and never fully either.",
   share: "My timeline: Walter. Heisenberg meter {meter}/100."},
  {id: "mrWhite", fallback: true, when: "", name: "Mr. White",
   summary: "In the end he was mostly what Jesse always called him: Mr. White.",
   share: "My timeline: Mr. White. Heisenberg meter {meter}/100."}
];
